# Generated by Django 2.0.6 on 2018-06-15 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='point',
            new_name='coordinates',
        ),
    ]
